"""Initial schema: entities, relations, constraints, provenance

Revision ID: f7e6e6058dcc
Revises: 
Create Date: 2026-01-23 18:22:54.755940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e6e6058dcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("priority IN ('hard', 'soft', 'preference')", name='valid_priority'),
    sa.CheckConstraint("type != ''", name='constraint_type_not_empty'),
    sa.CheckConstraint('length(type) <= 100', name='constraint_type_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_constraint_priority', 'constraints', ['priority'], unique=False)
    op.create_index('idx_constraint_type', 'constraints', ['type'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('children_ids', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("name != ''", name='entity_name_not_empty'),
    sa.CheckConstraint('length(type) <= 100', name='entity_type_length'),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_name', 'entities', ['name'], unique=False)
    op.create_index('idx_entity_parent', 'entities', ['parent_id'], unique=False)
    op.create_index('idx_entity_type', 'entities', ['type'], unique=False)
    op.create_table('provenance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('asserted_by', sa.Uuid(), nullable=False),
    sa.Column('asserted_at', sa.DateTime(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('validation_method', sa.String(length=100), nullable=True),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('measurement', 'inference', 'assertion', 'community', 'expert')", name='valid_source'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='confidence_bounds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provenance_asserted_by', 'provenance', ['asserted_by'], unique=False)
    op.create_index('idx_provenance_confidence', 'provenance', ['confidence'], unique=False)
    op.create_index('idx_provenance_source', 'provenance', ['source'], unique=False)
    op.create_table('relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('contract', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type != ''", name='relation_type_not_empty'),
    sa.CheckConstraint('from_entity_id != to_entity_id', name='no_self_loops'),
    sa.CheckConstraint('length(type) <= 100', name='relation_type_length'),
    sa.CheckConstraint('strength >= 0.0 AND strength <= 1.0', name='strength_bounds'),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relation_from', 'relations', ['from_entity_id'], unique=False)
    op.create_index('idx_relation_strength', 'relations', ['strength'], unique=False)
    op.create_index('idx_relation_to', 'relations', ['to_entity_id'], unique=False)
    op.create_index('idx_relation_type', 'relations', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_relation_type', table_name='relations')
    op.drop_index('idx_relation_to', table_name='relations')
    op.drop_index('idx_relation_strength', table_name='relations')
    op.drop_index('idx_relation_from', table_name='relations')
    op.drop_table('relations')
    op.drop_index('idx_provenance_source', table_name='provenance')
    op.drop_index('idx_provenance_confidence', table_name='provenance')
    op.drop_index('idx_provenance_asserted_by', table_name='provenance')
    op.drop_table('provenance')
    op.drop_index('idx_entity_type', table_name='entities')
    op.drop_index('idx_entity_parent', table_name='entities')
    op.drop_index('idx_entity_name', table_name='entities')
    op.drop_table('entities')
    op.drop_index('idx_constraint_type', table_name='constraints')
    op.drop_index('idx_constraint_priority', table_name='constraints')
    op.drop_table('constraints')
    # ### end Alembic commands ###
